/**
 * songs.js
 *
 * The app's songs
 */
window.songs = [
  // Taylor Swift's songs
  {
    songId: "SID-2001",
    artistId: "AID-1001",
    title: "Love Story",
    released: 2008,
    duration: 237,
    mediaUrl: "https://www.youtube.com/watch?v=8xg3vE8Ie_E",
    explicitLyrics: false,
    imgUrl: new URL("./picture/TS_fearless.jpg", import.meta.url),
  },
  {
    songId: "SID-2002",
    artistId: "AID-1001",
    title: "Shake It Off",
    released: 2014,
    duration: 242,
    mediaUrl: "https://www.youtube.com/watch?v=nfWlot6h_JM",
    explicitLyrics: false,
    imgUrl: new URL("./picture/TS_1989.jpg", import.meta.url),
  },
  {
    songId: "SID-2009",
    artistId: "AID-1001",
    title: "Blank Space",
    released: 2014,
    duration: 272,
    mediaUrl: "https://www.youtube.com/watch?v=e-ORhEE9VVg",
    explicitLyrics: false,
    imgUrl: new URL("./picture/TS_1989.jpg", import.meta.url),
  },
  {
    songId: "SID-2010",
    artistId: "AID-1001",
    title: "You Belong With Me",
    released: 2008,
    duration: 229,
    mediaUrl: "https://www.youtube.com/watch?v=VuNIsY6JdUw",
    explicitLyrics: false,
    imgUrl: new URL("./picture/TS_fearless.jpg", import.meta.url),
  },
  {
    songId: "SID-2017",
    artistId: "AID-1001",
    title: "Cardigan",
    released: 2020,
    duration: 275,
    mediaUrl: "https://www.youtube.com/watch?v=K-a8s8OLBSE",
    explicitLyrics: false,
    imgUrl: new URL("./picture/TS_fl.jpg", import.meta.url),
  },
  {
    songId: "SID-2018",
    artistId: "AID-1001",
    title: "Willow",
    released: 2020,
    duration: 256,
    mediaUrl: "https://www.youtube.com/watch?v=RsEZmictANA",
    explicitLyrics: false,
    imgUrl: new URL("./picture/TS_evermore.jpg", import.meta.url),
  },
  {
    songId: "SID-2019",
    artistId: "AID-1001",
    title: "Wildest Dreams",
    released: 2014,
    duration: 231,
    mediaUrl: "https://www.youtube.com/watch?v=IdneKLhsWOQ",
    explicitLyrics: false,
    imgUrl: new URL("./picture/TS_1989.jpg", import.meta.url),
  },
  {
    songId: "SID-2020",
    artistId: "AID-1001",
    title: "Bad Blood",
    released: 2014,
    duration: 231,
    mediaUrl: "https://www.youtube.com/watch?v=QcIy9NiNbmo",
    explicitLyrics: true,
    imgUrl: new URL("./picture/TS_1989.jpg", import.meta.url),
  },
  // Lady Gaga's songs
  {
    songId: "SID-2003",
    artistId: "AID-1002",
    title: "Bad Romance",
    released: 2009,
    duration: 295,
    mediaUrl: "https://www.youtube.com/watch?v=qrO4YZeyl0I",
    explicitLyrics: false,
    imgUrl: new URL("./picture/LG_tfm.jpg", import.meta.url),
  },
  {
    songId: "SID-2004",
    artistId: "AID-1002",
    title: "Poker Face",
    released: 2008,
    duration: 238,
    mediaUrl: "https://www.youtube.com/watch?v=bESGLojNYSo",
    explicitLyrics: false,
    imgUrl: new URL("./picture/LG_thefame.jpg", import.meta.url),
  },
  {
    songId: "SID-2011",
    artistId: "AID-1002",
    title: "Just Dance",
    released: 2008,
    duration: 244,
    mediaUrl: "https://www.youtube.com/watch?v=2Abk1jAONjw",
    explicitLyrics: false,
    imgUrl: new URL("./picture/LG_thefame.jpg", import.meta.url),
  },
  {
    songId: "SID-2012",
    artistId: "AID-1002",
    title: "Shallow",
    released: 2018,
    duration: 215,
    mediaUrl: "https://www.youtube.com/watch?v=bo_efYhYU2A",
    explicitLyrics: false,
    imgUrl: new URL("./picture/LG_btw.jpg", import.meta.url),
  },
  {
    songId: "SID-2021",
    artistId: "AID-1002",
    title: "Born This Way",
    released: 2011,
    duration: 260,
    mediaUrl: "https://www.youtube.com/watch?v=wV1FrqwZyKw",
    explicitLyrics: false,
    imgUrl: new URL("./picture/LG_btw.jpg", import.meta.url),
  },
  {
    songId: "SID-2022",
    artistId: "AID-1002",
    title: "Stupid Love",
    released: 2020,
    duration: 197,
    mediaUrl: "https://www.youtube.com/watch?v=5L6xyaeiV58",
    explicitLyrics: true,
    imgUrl: new URL("./picture/LG_Stupidlove.jpg", import.meta.url),
  },
  {
    songId: "SID-2027",
    artistId: "AID-1002",
    title: "Speechless",
    released: 2009,
    duration: 288,
    mediaUrl: "https://www.youtube.com/watch?v=7zc5Cbf9E8o",
    explicitLyrics: false,
    imgUrl: new URL("./picture/LG_tfm.jpg", import.meta.url),
  },
  {
    songId: "SID-2028",
    artistId: "AID-1002",
    title: "Dance in the Dark",
    released: 2009,
    duration: 275,
    mediaUrl: "https://www.youtube.com/watch?v=qaxPj1rqntY",
    explicitLyrics: false,
    imgUrl: new URL("./picture/LG_tfm.jpg", import.meta.url),
  },
  {
    songId: "SID-2029",
    artistId: "AID-1002",
    title: "Alejandro",
    released: 2009,
    duration: 242,
    mediaUrl: "https://www.youtube.com/watch?v=niqrrmev4mA",
    explicitLyrics: false,
    imgUrl: new URL("./picture/LG_tfm.jpg", import.meta.url),
  },
  {
    songId: "SID-2030",
    artistId: "AID-1002",
    title: "Monster",
    released: 2009,
    duration: 261,
    mediaUrl: "https://www.youtube.com/watch?v=dDvEY8LT4x0",
    explicitLyrics: false,
    imgUrl: new URL("./picture/LG_tfm.jpg", import.meta.url),
  },
  {
    songId: "SID-2031",
    artistId: "AID-1002",
    title: "So Happy I Could Die",
    released: 2009,
    duration: 271,
    mediaUrl: "https://www.youtube.com/watch?v=5TyO3eW7PBU",
    explicitLyrics: false,
    imgUrl: new URL("./picture/LG_tfm.jpg", import.meta.url),
  },
  {
    songId: "SID-2032",
    artistId: "AID-1002",
    title: "Teeth",
    released: 2009,
    duration: 255,
    mediaUrl: "https://www.youtube.com/watch?v=U8ovqbwzZ6w",
    explicitLyrics: true,
    imgUrl: new URL("./picture/LG_tfm.jpg", import.meta.url),
  },
  // Lana Del Rey's songs
  {
    songId: "SID-2005",
    artistId: "AID-1003",
    title: "Born to Die",
    released: 2012,
    duration: 283,
    mediaUrl: "https://www.youtube.com/watch?v=Bag1gUxuU0g",
    explicitLyrics: true,
    imgUrl: new URL("./picture/btd.jpg", import.meta.url),
  },
  {
    songId: "SID-2006",
    artistId: "AID-1003",
    title: "Summertime Sadness",
    released: 2012,
    duration: 266,
    mediaUrl: "https://www.youtube.com/watch?v=TdrL3QxjyVw",
    explicitLyrics: false,
    imgUrl: new URL("./picture/BTD.jpg", import.meta.url),
  },
  {
    songId: "SID-2013",
    artistId: "AID-1003",
    title: "Young and Beautiful",
    released: 2013,
    duration: 211,
    mediaUrl: "https://www.youtube.com/watch?v=o_1aF54DO60",
    explicitLyrics: false,
    imgUrl: new URL("./picture/lovenb.jpg", import.meta.url),
  },
  {
    songId: "SID-2014",
    artistId: "AID-1003",
    title: "Blue Jeans",
    released: 2012,
    duration: 228,
    mediaUrl: "https://www.youtube.com/watch?v=JRWox-i6aAk",
    explicitLyrics: false,
    imgUrl: new URL("./picture/bluejean.jpg", import.meta.url),
  },
  {
    songId: "SID-2033",
    artistId: "AID-1003",
    title: "Dark Paradise",
    released: 2012,
    duration: 257,
    mediaUrl: "https://www.youtube.com/watch?v=mnz-59ABFAw",
    explicitLyrics: true,
    imgUrl: new URL("./picture/BTD.jpg", import.meta.url),
  },
  {
    songId: "SID-2034",
    artistId: "AID-1003",
    title: "National Anthem",
    released: 2012,
    duration: 231,
    mediaUrl: "https://www.youtube.com/watch?v=sxDdEPED0h8",
    explicitLyrics: true,
    imgUrl: new URL("./picture/BTD.jpg", import.meta.url),
  },
  {
    songId: "SID-2035",
    artistId: "AID-1003",
    title: "Video Games",
    released: 2011,
    duration: 297,
    mediaUrl: "https://www.youtube.com/watch?v=cE6wxDqdOV0",
    explicitLyrics: false,
    imgUrl: new URL("./picture/BTD.jpg", import.meta.url),
  },
  {
    songId: "SID-2036",
    artistId: "AID-1003",
    title: "Blue Velvet",
    released: 2012,
    duration: 167,
    mediaUrl: "https://www.youtube.com/watch?v=HLEA3bc-3p0",
    explicitLyrics: false,
    imgUrl: new URL("./picture/BTD.jpg", import.meta.url),
  },
  {
    songId: "SID-2037",
    artistId: "AID-1003",
    title: "Ride",
    released: 2012,
    duration: 261,
    mediaUrl: "https://www.youtube.com/watch?v=Py_-3di1yx0",
    explicitLyrics: true,
    imgUrl: new URL("./picture/BTD.jpg", import.meta.url),
  },
  {
    songId: "SID-2038",
    artistId: "AID-1003",
    title: "Cola",
    released: 2012,
    duration: 270,
    mediaUrl: "https://www.youtube.com/watch?v=JRWox-i6aAk",
    explicitLyrics: true,
    imgUrl: new URL("./picture/BTD.jpg", import.meta.url),
  },
  {
    songId: "SID-2039",
    artistId: "AID-1003",
    title: "American",
    released: 2012,
    duration: 244,
    mediaUrl: "https://www.youtube.com/watch?v=4ze4o-l_Mxw",
    explicitLyrics: true,
    imgUrl: new URL("./picture/BTD.jpg", import.meta.url),
  },
  {
    songId: "SID-2040",
    artistId: "AID-1003",
    title: "Diet Mountain Dew",
    released: 2012,
    duration: 243,
    mediaUrl: "https://www.youtube.com/watch?v=uO6j8OmJYxg",
    explicitLyrics: false,
    imgUrl: new URL("./picture/BTD.jpg", import.meta.url),
  },
  // Katy Perry's songs
  {
    songId: "SID-2007",
    artistId: "AID-1004",
    title: "Teenage Dream",
    released: 2010,
    duration: 229,
    mediaUrl: "https://www.youtube.com/watch?v=98WtmW-lfeE",
    explicitLyrics: false,
    imgUrl: new URL("./picture/KP_tn.jpg", import.meta.url),
  },
  {
    songId: "SID-2008",
    artistId: "AID-1004",
    title: "Firework",
    released: 2010,
    duration: 230,
    mediaUrl: "https://www.youtube.com/watch?v=QGJuMBdaqIw",
    explicitLyrics: false,
    imgUrl: new URL("./picture/KP_tn.jpg", import.meta.url),
  },
  {
    songId: "SID-2015",
    artistId: "AID-1004",
    title: "Roar",
    released: 2013,
    duration: 224,
    mediaUrl: "https://www.youtube.com/watch?v=CevxZvSJLk8",
    explicitLyrics: false,
    imgUrl: new URL("./picture/KP_roar.jpg", import.meta.url),
  },
  {
    songId: "SID-2016",
    artistId: "AID-1004",
    title: "Dark Horse",
    released: 2013,
    duration: 215,
    mediaUrl: "https://www.youtube.com/watch?v=0KSOMA3QBU0",
    explicitLyrics: false,
    imgUrl: new URL("./picture/KP_pris.jpg", import.meta.url),
  },
  {
    songId: "SID-2023",
    artistId: "AID-1004",
    title: "California Gurls",
    released: 2010,
    duration: 235,
    mediaUrl: "https://www.youtube.com/watch?v=F57P9C4SAW4",
    explicitLyrics: false,
    imgUrl: new URL("./picture/KP_tn.jpg", import.meta.url),
  },
  {
    songId: "SID-2024",
    artistId: "AID-1004",
    title: "E.T.",
    released: 2010,
    duration: 230,
    mediaUrl: "https://www.youtube.com/watch?v=t5Sd5c4o9UM",
    explicitLyrics: false,
    imgUrl: new URL("./picture/KP_tn.jpg", import.meta.url),
  },
  {
    songId: "SID-2025",
    artistId: "AID-1004",
    title: "Last Friday Night (T.G.I.F.)",
    released: 2010,
    duration: 231,
    mediaUrl: "https://www.youtube.com/watch?v=KlyXNRrsk4A",
    explicitLyrics: true,
    imgUrl: new URL("./picture/KP_tn.jpg", import.meta.url),
  },
  {
    songId: "SID-2026",
    artistId: "AID-1004",
    title: "The One That Got Away",
    released: 2010,
    duration: 242,
    mediaUrl: "https://www.youtube.com/watch?v=Ahha3Cqe_fk",
    explicitLyrics: false,
    imgUrl: new URL("./picture/KP_tn.jpg", import.meta.url),
  },
];
